language: node_js

node_js:
  - '0.8'
  - '0.10'
  - '0.12'
  - 6
  - 8
  - 12

before_script:
  - npm install coffee-script # workaround for https://github.com/caolan/nodeunit/pull/358

script:
  - npm run build
  - git diff lib || exit 1
  - npm test
